version: '3.8'

volumes:
  database_data:
  minio_data:

services:
  database:
    image: postgres:16
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'Test1234'
      POSTGRES_USER: api
      POSTGRES_DB: youtube
    ports:
      - 5432:5432

  minio:
    image: quay.io/minio/minio
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9090"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Test1234
    ports:
      - "9000:9000"
      - "9090:9090"

